---
name: Tests

# Note: Most of CI is run through garnix.io, but the Nix sandboxing they use
# doesn't play nice with our test suite, so we run it through GitHub Actions.
on:
  check_suite:
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      - name: Run tests
        run: nix build -L .#default.checks.tests
